### PR TITLE
Php 8 support

### PR DESCRIPTION
**Pull request by AlexAzartsev**

### CODE REVIEW

**Comment by asamofal** [comment]
@erdemkeren When it can be accepted?

**Comment by mrizkimaulidan** [comment]
any update for this PR?

**Comment by AlexAzartsev** [comment]
no updates, these changes tested for several months on live projects already and no issues were found

**Comment by erdemkeren** [comment]
@AlexAzartsev @mrizkimaulidan @asamofal sorry it took a very long time. I will work on this today around 19:00 CEST

**Review by erdemkeren — APPROVED** [review]
looks good 👏

**Pull request merged**
